# GENERATED by ggen from ggen/packs/ex4pm-plan-contract-pack/ontology.ttl.
# Do not edit this projection directly.

PROTOCOL = "ex4pm-plan/v1"
SUPPORTED_PROBLEM = "deterministic_graph"
SUPPORTED_SOLVER = "astar"
LIBRARY_SOLVERS = (
    "astar",
    "bfws",
    "iw",
)
OPERATIONS = (
    "capabilities",
    "solve",
)
AUTHORITY = "CONSTRUCT_ONLY"
ACTUATION = False
